"use client";

import { useEffect, useState } from "react";

const STORAGE_KEY = "nthlayer_disclaimer_accepted_v1";

export function DisclaimerModal() {
  const [open, setOpen] = useState(false);
  const [accepted, setAccepted] = useState(false);

  useEffect(() => {
    // Show on every fresh page load until accepted in this browser session
    const acceptedAt = sessionStorage.getItem(STORAGE_KEY);
    if (!acceptedAt) {
      setOpen(true);
    }
  }, []);

  function handleAccept() {
    if (!accepted) return;
    sessionStorage.setItem(STORAGE_KEY, new Date().toISOString());
    setOpen(false);
  }

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center px-4"
      style={{ background: "rgba(15, 23, 42, 0.6)", backdropFilter: "blur(4px)" }}
    >
      <div
        className="relative w-full max-w-lg bg-white rounded-xl shadow-2xl overflow-hidden"
        role="dialog"
        aria-modal="true"
      >
        {/* Header */}
        <div className="px-6 py-5 border-b border-gray-100 flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gray-900 shrink-0">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
              <rect x="1" y="1" width="22" height="22" stroke="white" strokeWidth="1.8" />
              <rect x="4.5" y="4.5" width="15" height="15" stroke="white" strokeWidth="1.5" />
              <rect x="7.5" y="7.5" width="9" height="9" stroke="white" strokeWidth="1.3" />
              <rect x="10" y="10" width="4" height="4" stroke="white" strokeWidth="1.1" />
            </svg>
          </div>
          <div>
            <h2 className="text-base font-bold text-gray-900">Welcome to Nth Layer</h2>
            <p className="text-xs text-gray-500">Experimental — please read before continuing</p>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-4 text-sm text-gray-700 leading-relaxed">
          <p>
            <strong>The Nth Layer Signal Portal</strong> generates product strategy reports, competitor
            teardowns and market intelligence for investors and operators.
          </p>

          <div className="rounded-lg bg-amber-50 border border-amber-200 p-4">
            <p className="text-amber-900 font-medium mb-2 flex items-center gap-2">
              <svg width="18" height="18" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
              </svg>
              This is an experimental product
            </p>
            <ul className="text-xs text-amber-900/80 space-y-1.5 ml-6 list-disc">
              <li>All analysis is generated by Large Language Models (LLMs).</li>
              <li>The output can be wrong, out of date, or incomplete.</li>
              <li>Always verify with primary sources before acting on it.</li>
              <li>Treat every report as a draft, not a fact.</li>
            </ul>
          </div>

          <p className="text-xs text-gray-500">
            By continuing, you acknowledge that the reports are AI-generated and may contain errors,
            and you accept responsibility for verifying any information before using it.
          </p>
        </div>

        {/* Footer */}
        <div className="px-6 py-5 border-t border-gray-100 bg-gray-50">
          <label className="flex items-start gap-3 mb-4 cursor-pointer">
            <input
              type="checkbox"
              checked={accepted}
              onChange={(e) => setAccepted(e.target.checked)}
              className="mt-0.5 w-4 h-4 rounded border-gray-300 text-gray-900 focus:ring-gray-900"
            />
            <span className="text-sm text-gray-700">
              I understand the reports are AI-generated and may be wrong. I will verify before using.
            </span>
          </label>
          <button
            onClick={handleAccept}
            disabled={!accepted}
            className="w-full rounded-md px-4 py-2.5 text-sm font-medium transition-opacity"
            style={{
              background: accepted ? "#1e293b" : "#cbd5e1",
              color: "#fff",
              cursor: accepted ? "pointer" : "not-allowed",
            }}
          >
            Accept &amp; Continue
          </button>
        </div>
      </div>
    </div>
  );
}
