name = "nthlayer-website-new"
compatibility_date = "2026-03-18"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[assets]
directory = "./_site"
binding = "ASSETS"

# Routes moved to nthlayer-portal worker
